package com.mlp.api.datatypes.chatgpt

import java.util.Objects
import com.fasterxml.jackson.annotation.JsonValue
import com.fasterxml.jackson.annotation.JsonProperty
import io.swagger.v3.oas.annotations.media.Schema

/**
* 
* Values: CHAT_COMPLETIONS,RESPONSES,REALTIME,ASSISTANTS,BATCH_PROCESSING,FINE_TUNING,EMBEDDINGS,IMAGE_GENERATION,IMAGE_EDIT,SPEECH_GENERATION,TRANSCRIPTION,SPEECH_TO_TEXT,MODERATIONS,COMPLETIONS
*/
enum class ModelRequestType(val value: kotlin.String) {

    @JsonProperty("CHAT_COMPLETIONS") CHAT_COMPLETIONS("CHAT_COMPLETIONS"),
    @JsonProperty("RESPONSES") RESPONSES("RESPONSES"),
    @JsonProperty("REALTIME") REALTIME("REALTIME"),
    @JsonProperty("ASSISTANTS") ASSISTANTS("ASSISTANTS"),
    @JsonProperty("BATCH_PROCESSING") BATCH_PROCESSING("BATCH_PROCESSING"),
    @JsonProperty("FINE_TUNING") FINE_TUNING("FINE_TUNING"),
    @JsonProperty("EMBEDDINGS") EMBEDDINGS("EMBEDDINGS"),
    @JsonProperty("IMAGE_GENERATION") IMAGE_GENERATION("IMAGE_GENERATION"),
    @JsonProperty("IMAGE_EDIT") IMAGE_EDIT("IMAGE_EDIT"),
    @JsonProperty("SPEECH_GENERATION") SPEECH_GENERATION("SPEECH_GENERATION"),
    @JsonProperty("TRANSCRIPTION") TRANSCRIPTION("TRANSCRIPTION"),
    @JsonProperty("SPEECH_TO_TEXT") SPEECH_TO_TEXT("SPEECH_TO_TEXT"),
    @JsonProperty("MODERATIONS") MODERATIONS("MODERATIONS"),
    @JsonProperty("COMPLETIONS") COMPLETIONS("COMPLETIONS")
}

