<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <packaging>pom</packaging>
    <modules>
        <module>mlp-datatypes</module>
        <module>mlp-sdk</module>
        <module>mlp-examples/mlp-fit-action</module>
        <module>mlp-examples/mlp-simple-action</module>
        <module>mlp-examples/mlp-client-app</module>
        <module>mlp-examples/mlp-rest-app</module>
        <module>mlp-examples/ai-proxy-client</module>
        <module>mlp-examples/mlp-asr-action</module>
    </modules>

    <groupId>com.mlp</groupId>
    <artifactId>mlp-java-sdk</artifactId>
    <version>${revision}</version>

    <name>mlp-java-sdk</name>
    <description>MLP Java SDK</description>

    <properties>
        <revision>2.2.4</revision>

        <branch.name.lower>local</branch.name.lower>
        <branch.name.python>local</branch.name.python>

        <java.version>17</java.version>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>

        <kotlin.version>1.8.22</kotlin.version>
        <coroutines.version>1.6.4</coroutines.version>
        <grpc.kotlin.version>1.4.1</grpc.kotlin.version>

        <!-- The version is the latest found here: https://search.maven.org/artifact/io.grpc/grpc-protobuf -->
        <!-- IMPORTANT: currently we support max 1.39.0 -->
        <grpc.version>1.60.2</grpc.version>

        <!-- the version is the latest found here: https://search.maven.org/search?q=a:protobuf-kotlin -->
        <!-- IMPORTANT: currently we support max 3.18.1 -->
        <!--        3.19.3 contains CVE-2024-7254-->
        <protobuf.version>3.25.6</protobuf.version>

        <slf4j.version>1.7.32</slf4j.version>

        <spring-boot.version>2.7.12</spring-boot.version>

        <mlp-core.version>20260209201531</mlp-core.version>
        <mlp-gateway.version>20260209201531</mlp-gateway.version>

        <mlp-grpc.version>2.0.2</mlp-grpc.version>
    </properties>

    <repositories>
        <repository>
            <id>nexus-public</id>
            <url>https://nexus.just-ai.com/repository/maven-public/</url>
        </repository>
    </repositories>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.google.protobuf</groupId>
                <artifactId>protobuf-bom</artifactId>
                <version>${protobuf.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>io.grpc</groupId>
                <artifactId>grpc-bom</artifactId>
                <version>${grpc.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <pluginRepositories>
        <pluginRepository>
            <id>nexus-public</id>
            <url>https://nexus.just-ai.com/repository/maven-public/</url>
        </pluginRepository>
    </pluginRepositories>

    <distributionManagement>
        <repository>
            <id>nexus</id>
            <url>${deploymentRepo}</url>
        </repository>
    </distributionManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>flatten-maven-plugin</artifactId>
                    <version>1.5.0</version>
                    <configuration>
                        <updatePomFile>true</updatePomFile>
                        <flattenMode>resolveCiFriendliesOnly</flattenMode>
                    </configuration>
                    <executions>
                        <execution>
                            <id>flatten</id>
                            <phase>process-resources</phase>
                            <goals>
                                <goal>flatten</goal>
                            </goals>
                        </execution>
                        <execution>
                            <id>flatten.clean</id>
                            <phase>clean</phase>
                            <goals>
                                <goal>clean</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

    <profiles>
        <profile>
            <id>internal-snapshot</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <properties>
                <deploymentRepo>https://nexus.just-ai.com/repository/maven-snapshots/</deploymentRepo>
            </properties>
        </profile>

        <profile>
            <id>internal-release</id>
            <properties>
                <deploymentRepo>https://nexus.just-ai.com/repository/maven-releases/</deploymentRepo>
            </properties>
        </profile>

        <profile>
            <id>nexus-open-snapshot</id>
            <properties>
                <deploymentRepo>https://nexus-open.just-ai.com/repository/maven-snapshots/</deploymentRepo>
            </properties>
        </profile>

        <profile>
            <id>nexus-open-release</id>
            <properties>
                <deploymentRepo>https://nexus-open.just-ai.com/repository/maven-releases/</deploymentRepo>
            </properties>
        </profile>
    </profiles>
</project>
