openapi: 3.0.1
info:
  title: Datatypes specification for NLP task type
  version: v0
paths: { }

components:
  schemas:
    Text:
      type: object
      required:
        - text
      properties:
        text:
          type: string
    #Deprecated
    Texts:
      type: object
      required:
        - texts
      properties:
        texts:
          type: array
          items:
            type: string
